/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jbox2d.java-conventions")
}

dependencies {
    testImplementation("junit:junit:4.13.1")
}

description = "jbox2d-library"
