/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "jbox2d"
include(":jbox2d-serialization")
include(":jbox2d-testbed")
include(":jbox2d-library")
include(":jbox2d-testbed-javafx")
include(":jbox2d-testbed-jogl")
