/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jbox2d.java-conventions")
}

dependencies {
    api(project(":jbox2d-library"))
    api("com.google.protobuf:protobuf-java:3.16.3")
}

description = "jbox2d-serialization"
