/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jbox2d.java-conventions")
}

dependencies {
    api(project(":jbox2d-library"))
    api(project(":jbox2d-serialization"))
    api(project(":jbox2d-testbed"))
    api("org.jogamp.gluegen:gluegen-rt-main:2.1.2")
    api("org.jogamp.jogl:jogl-all-main:2.1.2")
}

description = "jbox2d-testbed-jogl"
