/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jbox2d.java-conventions")
}

dependencies {
    api("org.apache.commons:commons-math3:3.2")
    api(project(":jbox2d-library"))
    api(project(":jbox2d-serialization"))
    api(project(":jbox2d-testbed"))
    api("org.openjfx:javafx-base:13.0.2")
    api("org.openjfx:javafx-controls:13.0.2")
}

description = "jbox2d-testbed-javafx"
