/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jbox2d.java-conventions")
}

dependencies {
    api("org.apache.commons:commons-math3:3.2")
    api(project(":jbox2d-library"))
    api("org.slf4j:slf4j-api:1.6.1")
    api("org.slf4j:slf4j-log4j12:1.6.1")
    api("log4j:log4j:1.2.14")
    api(project(":jbox2d-serialization"))
    api("com.google.guava:guava:14.0.1")
}

description = "jbox2d-testbed"
